### ISSUE TITLE
Create Production Container Image for v0.1 RSNA 2021

### ISSUE THREAD

**Issue by whoisj** [Project-MONAI/monai-deploy-app-server#10]
Create a dockerfile used for the generation of a production container image.

The production container image should:
- Use the Inference Service Base Container as its base.
- Include the Inference Service software package.
- Have the minimum number of steps possible to minimize:
  - Container build times.
  - Impact on CI/CD.

**Comment by dbericat** [comment]
@Danulf @whoisj same, please close. Same considerations as base container. Thanks!

**Comment by Danulf** [comment]
closing; won't do.
