### ISSUE TITLE
Create Base Container Image for Inference Server v0.1 RSNA 2021

### ISSUE THREAD

**Issue by whoisj** [Project-MONAI/monai-deploy-app-server#6]
Create a dockerfile used for the generation of a base container image.

The base container image should include:
- Base operating system up-to-date with patches.
- All `apt`, `dpkg`, `snap`, or other required package managed based installations.
- As many required Python wheel files installed as possible.

With the goals of:
- Minimizing the amount of network activity (ala downloads) as possible when building the production container image.
- Creating a stable base for the application code.
- Minimizing slow or unstable portions of CI
- Minimizing the change that an external package update could break the build.

**Comment by Danulf** [comment]
We modified this to simply build the image. From a licensing POV, that is the safest approach. Can we close this issue?

**Comment by dbericat** [comment]
> We modified this to simply build the image. From a licensing POV, that is the safest approach. Can we close this issue?

Yep. Please close it. Backlog, closed section. Or 0.1, closed. Thanks!

**Comment by Danulf** [comment]
Issue should be closed.
